server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://user:admin123@localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false
security:
  basic:
    enabled: true
  user:
    name: user
    password: admin123