server:
  port: 7901
user:
  userServicePath: http://localhost:7900/simple/
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    service-url:
      defaultZone: http://user:admin123@localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true